export const ACCOUNT_ROLES_FETCHED = 'ACCOUNT_ROLES_FETCHED';

export const WALLET_INDEX_SELECTED = 'WALLET_INDEX_SELECTED';

export const REGISTER_AS_OEM_SENT = 'REGISTER_AS_OEM_SENT';

export const REGISTER_AS_OEM_FAILED_TO_SEND = 'REGISTER_AS_OEM_FAILED_TO_SEND';

export const REGISTER_AS_OEM_FAILED_NOTIFIED = 'REGISTER_AS_OEM_FAILED_NOTIFIED';

export const REGISTERED_AS_OEM = 'REGISTERED_AS_OEM';

export const REGISTER_AS_DEALER_SENT = 'REGISTER_AS_DEALER_SENT';

export const REGISTER_AS_DEALER_FAILED_TO_SEND = 'REGISTER_AS_DEALER_FAILED_TO_SEND';

export const REGISTER_AS_DEALER_FAILED_NOTIFIED = 'REGISTER_AS_DEALER_FAILED_NOTIFIED';

export const REGISTERED_AS_DEALER = 'REGISTERED_AS_DEALER';

export const FETCHED_OEM_NAME = 'FETCHED_OEM_NAME';
