export const VEHICLE_MANUFACTURE_SENT = 'VEHICLE_MANUFACTURE_SENT';

export const VEHICLE_MANUFACTURED = 'VEHICLE_MANUFACTURED';

export const VEHICLE_MANUFACTURED_DISMISSED = 'VEHICLE_MANUFACTURED_DISMISSED';

export const VEHICLE_MANUFACTURE_FAILED = 'VEHICLE_MANUFACTURE_FAILED';

export const VEHICLE_MANUFACTURE_FAILURE_DISMISSED = 'VEHICLE_MANUFACTURE_FAILURE_DISMISSED';

export const FETCHED_VEHICLE = 'FETCHED_VEHICLE';

export const VEHICLE_TRANSFER_SENT = 'VEHICLE_TRANSFER_SENT';

export const VEHICLE_TRANSFERRED = 'VEHICLE_TRANSFERRED';

export const VEHICLE_TRANSFERRED_DISMISSED = 'VEHICLE_TRANSFERRED_DISMISSED';

export const VEHICLE_TRANSFER_FAILED = 'VEHICLE_TRANSFER_FAILED';

export const VEHICLE_TRANSFER_FAILURE_DISMISSED = 'VEHICLE_TRANSFER_FAILURE_DISMISSED';
